### ISSUE TITLE
Rahel Semu: Working With Code

### ISSUE THREAD

**Issue by Rahela-HYF** [HackYourFutureBelgium/hack-my-future#2]
__Skill to develop__:html,CSS and Java Script

__Why this skill? because this are the basics to develop website and  this will help me to become front end developer:

__How to recognize when I've learned it__: by doing my assignment and develop website.

Some good study resources: kahan Acadamy
* ...
* ...

**Comment by colevandersWands** [comment]
@Rahela-HYF, study-issues should be in your fork of this repository.  Glad to see you're already organizing your study :)
